# PostgreSQL 9.5 setup adapted from: https://github.com/travis-ci/travis-ci/issues/4264
sudo: false
dist: trusty
script:
  - bundle exec rspec --format progress --tag ~type:acceptance
branches:
  only:
    - master
language: ruby
rvm:
  - "2.3.3"
cache: bundler
bundler_args: --without production --retry=6
