# PostgreSQL 9.5 setup adapted from: https://github.com/travis-ci/travis-ci/issues/4264
branches:
  only:
    - master
sudo: false
dist: trusty
language: ruby
rvm: 2.6.1
cache: bundler
before_install:
  - gem install bundler --force
bundler_args: --without production --retry=6
script:
  - bundle exec rspec --format progress --tag ~type:acceptance
