# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5b512fafe03c3e4e0a8ffc7bb68a3d6cbe549deb7296990091d8a18ff910728a5916e72a2e1d783138a1f0cfc9d36e6a09dc74c88ba00c5a9a7b3d86b81cff
  openstax:
    biglearn:
      scheduler:
        url: http://localhost:3000
        token: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_TOKEN'] || '664a21c50a6e96f51383d3642267e8c8dd32d625cca464c4448bea22a82972ef688594f24bb5c1c01ef69d0cd4949166e631c9acad142d35bf8e098c14dec2f2' %>
        client_id: ~
        secret: ~
        stub: true
  exception:
    environment_name: <%= ENV['EXCEPTION_ENVIRONMENT_NAME'] || 'dev' %>
    contact_name: <%= ENV['EXCEPTION_CONTACT_NAME'] || 'OpenStax' %>
    sender: <%= ENV['EXCEPTION_SENDER'] || 'sender@example.org' %>
    recipients: <%= (ENV['EXCEPTION_RECIPIENTS'] || 'recipients@example.org').split.compact %>

test:
  secret_key_base: 280a85f7103c2d628ae14bfeb69187f6ddbffc405170f85037beb43e444aeed6b9621ef2b08ae6d0e9e0b52003832c5ef481088d2de5bfd13584677172fe471f
  openstax:
    biglearn:
      scheduler:
        url: http://localhost:3000
        token: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_TOKEN'] || 'c88e21d6d158d5200ce4ace9592c3acea06e066ec1b92bc623f7e76cd02b7f8736143afaa1551802f6787bcd0135e0157beace5bb33ed026dbedb53848b75ded' %>
        client_id: ~
        secret: ~
        stub: true
  exception:
    environment_name: <%= ENV['EXCEPTION_ENVIRONMENT_NAME'] || 'test' %>
    contact_name: <%= ENV['EXCEPTION_CONTACT_NAME'] || 'OpenStax' %>
    sender: <%= ENV['EXCEPTION_SENDER'] || 'sender@example.org' %>
    recipients: <%= (ENV['EXCEPTION_RECIPIENTS'] || 'recipients@example.org').split.compact %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  openstax:
    biglearn:
      scheduler:
        url: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_URL'] %>
        token: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_TOKEN'] %>
        client_id: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_CLIENT_ID'] %>
        secret: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_SECRET'] %>
        stub: false
  exception:
    environment_name: <%= ENV['EXCEPTION_ENVIRONMENT_NAME'] %>
    contact_name: <%= ENV['EXCEPTION_CONTACT_NAME'] %>
    sender: <%= ENV['EXCEPTION_SENDER'] %>
    recipients: <%= (ENV['EXCEPTION_RECIPIENTS'] || '').split.compact %>
