# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5b512fafe03c3e4e0a8ffc7bb68a3d6cbe549deb7296990091d8a18ff910728a5916e72a2e1d783138a1f0cfc9d36e6a09dc74c88ba00c5a9a7b3d86b81cff
  openstax:
    biglearn:
      scheduler:
        client_id: ~
        secret: ~
        url: http://localhost:3000
        stub: true

test:
  secret_key_base: 280a85f7103c2d628ae14bfeb69187f6ddbffc405170f85037beb43e444aeed6b9621ef2b08ae6d0e9e0b52003832c5ef481088d2de5bfd13584677172fe471f
  openstax:
    biglearn:
      scheduler:
        client_id: ~
        secret: ~
        url: http://localhost:3000
        stub: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  openstax:
    biglearn:
      scheduler:
        client_id: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_CLIENT_ID'] %>
        secret: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_SECRET'] %>
        url: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_URL'] %>
        stub: false
