# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5b512fafe03c3e4e0a8ffc7bb68a3d6cbe549deb7296990091d8a18ff910728a5916e72a2e1d783138a1f0cfc9d36e6a09dc74c88ba00c5a9a7b3d86b81cff
  openstax:
    biglearn:
      scheduler:
        url: http://localhost:3000
        token: <%= ENV['OPENSTAX_BIGLEARN_SCHEDULER_TOKEN'] || 'c88e21d6d158d5200ce4ace9592c3acea06e066ec1b92bc623f7e76cd02b7f8736143afaa1551802f6787bcd0135e0157beace5bb33ed026dbedb53848b75ded' %>
        client_id: ~
        secret: ~
        stub: true

test:
  secret_key_base: 280a85f7103c2d628ae14bfeb69187f6ddbffc405170f85037beb43e444aeed6b9621ef2b08ae6d0e9e0b52003832c5ef481088d2de5bfd13584677172fe471f
  openstax:
    biglearn:
      scheduler:
        url: http://localhost:3000
        token: c88e21d6d158d5200ce4ace9592c3acea06e066ec1b92bc623f7e76cd02b7f8736143afaa1551802f6787bcd0135e0157beace5bb33ed026dbedb53848b75ded
        client_id: ~
        secret: ~
        stub: true
